export const COMMNETS = Object.freeze({
  OPENSOURCE_DASHBOARD_ACTIVE: 'opensource_dashboard:active',
  OPENSOURCE_TOYS: 'opensource_toys',
  RECENT_POSTS: 'recent_posts_inject',
  RECENT_STAR: 'recent_star_inject',
  RANDOM_GITHUB_STARS: 'random_github_stars_inject',
  FOOTER: 'footer_inject',
  MOTTO: 'motto',
  GH_STARS: 'GH_STARS',
  GH_COMMITS_THIS_YEAR: 'GH_COMMITS_THIS_YEAR',
  GH_PRS: 'GH_PRS',
  GH_ISSUES: 'GH_ISSUES',
  GH_CONTRIBS: 'GH_CONTRIBS',
  GH_RANK_NODE: 'GH_RANK_NODE',
})
